Update ACTmapi sources
osmlab/editor-layer-index pull request #2341
Opened 2024-05-28 21:07 UTC by arch0345

Closes #2340

2024-05-29 05:56 UTC, andrewharvey requested changes
Thanks for the PR. I've added one comment.

I think leaving the WMTS only endpoints is okay, I assume that means only JOSM would support them?

2024-05-29 05:56 UTC, andrewharvey commented on sources/oceania/au/act/ACTmapi-Imagery202402.geojson
> +        "min_zoom": 5
It looks like the data only starts appearing from zoom 10, so should we set this to 10 instead?

2024-05-29 19:06 UTC, arch0345 commented
> I think leaving the WMTS only endpoints is okay, I assume that means only JOSM would support them?

Yeah that's correct

2024-05-30 00:43 UTC, andrewharvey commented
Thanks looks good. I'll try to keep on eye on the older imagery as it would be nice to retain that in the index, and also for OHM's ELI.

2024-05-30 00:44 UTC, merged