Add PMGSY GeoSadak 2022 (India)
osmlab/editor-layer-index pull request #2351
Opened 2024-06-19 13:31 UTC by Vonter

Layer information from https://github.com/datameet/pmgsy-geosadak

2024-06-20 19:21 UTC, planemad commented
The also includes OSM data and Mapbox Satellite imagery, which overall should be fine for tracing on OSM, but not for other uses. We should correct the license to say ODbL to make this clear.

If the tiles have only the Geosadak data, that would make it a truly CC-by / https://data.gov.in/Godl level tile layer, but we could do that in the future.

Let me also switch the token with one that is specific for OSM India Community use.

2024-06-20 19:37 UTC, planemad requested changes

2024-06-20 19:37 UTC, planemad commented on sources/asia/in/India-PMGSY.geojson
> +        "url": "https://api.mapbox.com/styles/v1/planemad/cknj1leps0ywv17lrj8d16vnj/tiles/256/{zoom}/{x}/{y}?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiY2t6enBzbzdsMGNrZzNjbXhyeWdkeW55MCJ9.tAP01enwl
```suggestion
        "url": "https://api.mapbox.com/styles/v1/planemad/cknj1leps0ywv17lrj8d16vnj/tiles/256/{zoom}/{x}/{y}?access_token=pk.eyJ1Ijoib3NtaW5kaWEiLCJhIjoiY2x2M2h0dmtnMDB5MzJqbzBsNmhwczJubSJ9.XE-a2USKZUYH4t8rTFEnmg",
```

2024-06-20 19:37 UTC, planemad commented on sources/asia/in/India-PMGSY.geojson
> +        "url": "https://api.mapbox.com/styles/v1/planemad/cknj1leps0ywv17lrj8d16vnj/tiles/256/{zoom}/{x}/{y}?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiY2t6enBzbzdsMGNrZzNjbXhyeWdkeW55MCJ9.tAP01enwl
Token from the Mapbox `osmindia` account for OSM community use

2024-06-20 19:37 UTC, planemad commented on sources/asia/in/India-PMGSY.geojson
> +        "name": "PMGSY GeoSadak",
```suggestion
        "name": "PMGSY GeoSadak - India Rural Roads Open Data",
```

2024-06-20 19:37 UTC, planemad commented on sources/asia/in/India-PMGSY.geojson
> +        "name": "PMGSY GeoSadak",
More informative name for someone unaware of PMGSY

2024-06-20 19:37 UTC, planemad commented on sources/asia/in/India-PMGSY.geojson
> +            "text": "PMGSY National GIS - Open Data",
```suggestion
            "text": "PMGSY National GIS - Open Data",
            "html": "<a href='https://geosadak-pmgsy.nic.in/opendata/' target='_blank'>PMGSY Rural Connectivity Dataset, Government Open Data License</a> | <a href='https://www.mapbox.com/about/maps/' target='_blank' title='Mapbox' aria-label='Mapbox'>© Mapbox</a> | <a href='https://www.openstreetmap.org/about/' target='_blank' title='OpenStreetMap' aria-label='OpenStreetMap'>© OpenStreetMap</a> | <a href='https://www.maxar.com/' target='_blank' title='Maxar' aria-label='Maxar'>© Maxar</a>",
```

2024-06-20 19:37 UTC, planemad commented on sources/asia/in/India-PMGSY.geojson
> +            "text": "PMGSY National GIS - Open Data",
Making sure all sources are attributed

2024-06-21 03:15 UTC, Vonter commented
Thanks a lot for the suggestions @planemad, I have included them in the JSON.

2024-06-21 15:40 UTC, Vonter commented
@planemad it looks like the OSM India Community token fails to load the tiles due to an access forbidden 403 error. I have reverted back to the original token for now, but if there's a way to fix the access with the new token, I could try it out.

2024-06-22 04:17 UTC, planemad commented on sources/asia/in/India-PMGSY.geojson
> +        "url": "https://api.mapbox.com/styles/v1/planemad/cknj1leps0ywv17lrj8d16vnj/wmts?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiY2l2eDhnNzNpMDAwNzJ5cGowcnpiMXJkdyJ9.NljuPglsRA3mTGf-4CLIEg",
```suggestion
        "url": "https://api.mapbox.com/styles/v1/planemad/cknj1leps0ywv17lrj8d16vnj/wmts?access_token=pk.eyJ1Ijoib3NtaW5kaWEiLCJhIjoiY2x4bm44YTVsMDR5bzJyczY5MjBoa2Q5aSJ9.r1MPugHw49L3kViEaWhBWA",
```

2024-06-22 04:18 UTC, planemad commented on sources/asia/in/India-PMGSY.geojson
> +        "url": "https://api.mapbox.com/styles/v1/planemad/cknj1leps0ywv17lrj8d16vnj/wmts?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiY2l2eDhnNzNpMDAwNzJ5cGowcnpiMXJkdyJ9.NljuPglsRA3mTGf-4CLIEg",
@Vonter fixed the token after testing

2024-06-22 17:11 UTC, Vonter commented on sources/asia/in/India-PMGSY.geojson
> +        "url": "https://api.mapbox.com/styles/v1/planemad/cknj1leps0ywv17lrj8d16vnj/wmts?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiY2l2eDhnNzNpMDAwNzJ5cGowcnpiMXJkdyJ9.NljuPglsRA3mTGf-4CLIEg",
Thanks! Works perfectly now :+1:

2024-08-17 23:46 UTC, merged