Add Mesa County GIS 2024 imagery
osmlab/editor-layer-index pull request #2368
Opened 2024-06-24 05:42 UTC by acarasimon96

This high-resolution aerial imagery covers only cities, towns, and rural communities in [Mesa County, Colorado, USA](https://en.wikipedia.org/wiki/Mesa_County,_Colorado).

2024-07-13 14:25 UTC, acarasimon96 commented
I noticed that this PR has been stuck at "1 workflow awaiting approval" since I submitted it. Any update on getting this looked at?

2024-07-28 17:53 UTC, arch0345 requested changes

2024-07-28 17:53 UTC, arch0345 commented on sources/north-america/us/co/MesaCountyValleywideImagery2024.geojson
> +        "type": "Polygon",
```suggestion
        "type": "MultiPolygon",
```
It looks like this geojson is made up of multiple outer rings, so the type `MultiPolygon` should be used. Here's the formatting for geojson multipolygons (basically an array of polygons): https://docs.mapbox.com/android/java/api/libjava-geojson/5.8.0/com/mapbox/geojson/MultiPolygon.html

2024-07-28 21:55 UTC, acarasimon96 commented on sources/north-america/us/co/MesaCountyValleywideImagery2024.geojson
> +        "type": "Polygon",
Just got this done. I also reordered the coordinates to follow the right-hand rule to satisfy the warning about it on geojson.io. I am a novice in dealing with GeoJSON, so further review is appreciated.

2024-07-29 19:24 UTC, arch0345 approved these changes

2024-08-17 23:43 UTC, merged