Update imagery from city of Bern
osmlab/editor-layer-index pull request #2409
Opened 2024-07-25 14:40 UTC by habi

- Removed Stadt_Bern_10cm-2016-WMS.geojson and Stadt_Bern_10cm-2020-WMS.geojson, as "Dienst eingestell", e.g. discontinued
- Added Stadt_Bern-Orthofotos-2023-WMTS.geojson, is an updated copy of Stadt_Bern_10cm-2020-WMS.geojson

2024-07-26 23:24 UTC, arch0345 requested changes

2024-07-26 23:24 UTC, arch0345 commented on sources/europe/ch/Stadt_Bern-Orthofotos-2023-WMTS.geojson
> +        "url": "https://map.bern.ch/arcgis/services/Geoportal/Orthofoto_2023/MapServer/WmsServer?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&CRS={proj}
This looks like the URL formatting for a WMS endpoint, not WMTS

2024-07-29 13:03 UTC, habi commented on sources/europe/ch/Stadt_Bern-Orthofotos-2023-WMTS.geojson
> +        "url": "https://map.bern.ch/arcgis/services/Geoportal/Orthofoto_2023/MapServer/WmsServer?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&CRS={proj}
I copy-pasted the wrong line from https://josm.openstreetmap.de/wiki/Maps/Switzerland#StadtBern10cm2023

Does ELI offer a 'mirror' option?

2024-07-29 13:12 UTC, habi commented
Fixes https://github.com/osmlab/editor-layer-index/issues/2365 if accepted

2024-07-29 19:18 UTC, arch0345 commented on sources/europe/ch/Stadt_Bern-Orthofotos-2023-WMTS.geojson
> +        "url": "https://map.bern.ch/arcgis/services/Geoportal/Orthofoto_2023/MapServer/WmsServer?FORMAT=image/png&TRANSPARENT=TRUE&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&LAYERS=0&STYLES=&CRS={proj}
> Does ELI offer a 'mirror' option?

Not that I know of, however it looks like #816 would add support for this

2024-08-09 17:16 UTC, arch0345 approved these changes

2024-08-09 17:25 UTC, arch0345 commented
@grischard if you have the time, could you please review this PR? Thanks

2024-08-10 21:58 UTC, merged