Moldova imagery updates
osmlab/editor-layer-index pull request #2458
Opened 2024-08-22 22:04 UTC by Oni-DOS

Added new imagery and added up to date data for old ones, removed 2016 reserver server because this server will be shutted down this year. Also about the permitting of using these imageries: the AGCC (later known as ARFC), the owner and maintainer of these imagery changed the access and using constraints to "No limitations to public access" and "No conditions to access and use", these can be seen in the imageries files metadata at license_url:. So this means that these imagery can be used without any constraints in OSM.

2024-08-22 22:19 UTC, Oni-DOS commented
Is the available_projections parameter very important for merging these files in the main branch?

2024-08-23 03:42 UTC, arch0345 commented
> Is the available_projections parameter very important for merging these files in the main branch?

Yes, this is needed for editors like iD to know what value(s) to use for the {proj} parameter in the url

2024-08-23 04:41 UTC, arch0345 requested changes

2024-08-23 04:41 UTC, arch0345 commented on sources/europe/md/Orthophoto_2007_38towns.geojson
> +        "type": "Polygon",
It looks like this geojson is made up of multiple outer rings, so the type MultiPolygon should be used. Here's the formatting for geojson multipolygons (basically an array of polygons): https://docs.mapbox.com/android/java/api/libjava-geojson/5.8.0/com/mapbox/geojson/MultiPolygon.html
```suggestion
        "type": "MultiPolygon",
```

2024-08-23 04:48 UTC, arch0345 commented
There should be an extra pair of brackets between each outer ring, see the documentation url I linked

2024-08-23 05:48 UTC, Oni-DOS commented
So what is the problem now?

2024-08-23 06:01 UTC, arch0345 commented
It looks like some of these layers have a `wms:` prefix in the url, which seems to come from the  JOSM index. This prefix should be omitted in ELI

I can't figure out where the geometry error is coming from

2024-08-23 06:20 UTC, Oni-DOS commented
I checked with JOSM these files for geometry errors and it didn't finded them

2024-08-24 01:49 UTC, arch0345 approved these changes

2024-08-24 01:49 UTC, merged