Create SouthTyrol-Cadastre.geojson
osmlab/editor-layer-index pull request #2479
Opened 2024-09-01 23:47 UTC by mwild500

Cadastre map from wms https://geoservices5.civis.bz.it/geoserver/p_bz-Cadastre/wms?request=getCapabilities

2024-09-13 11:20 UTC, matheusgomesms commented
Thank you!

Is this layer working? I didn't manage to make it work on iD, JOSM, or even in their GeoServer.

2025-06-17 23:45 UTC, andrewharvey commented on sources/europe/it/SouthTyrol-Cadastre.geojson
> +            "required": false
if the data is CC BY then attribution is required so should be `required: true`

2025-06-17 23:53 UTC, andrewharvey requested changes
Thanks for the PR and apologies it's been missed.

The service is working for me, but it looks like it would work better as an overlay above imagery rather than a background map. Could you set `overlay: true`? Per the schema at https://github.com/osmlab/editor-layer-index/blob/d3f5b9255d49d23e7f9d107002515dfa7fcfbab0/schema.json#L162

2025-06-17 23:55 UTC, andrewharvey commented on sources/europe/it/SouthTyrol-Cadastre.geojson
> +        "best": true
Could we remove `best: true` this should be for imagery layers only.

2025-06-17 23:56 UTC, andrewharvey commented on sources/europe/it/SouthTyrol-Cadastre.geojson
> +        "category": "photo",
could you change the category to either `map` or `other` since it's not an orthophoto. https://github.com/osmlab/editor-layer-index/blob/gh-pages/CONTRIBUTING.md#categories

2025-06-17 23:57 UTC, andrewharvey commented on sources/europe/it/SouthTyrol-Cadastre.geojson
> +        "end_date": "2024-09-02",
If the data is continually updated, best leave off the start/end dates. Unless you know the data is fixed at this time period?

2025-06-17 23:59 UTC, andrewharvey commented
Could you also please remind me where the CC BY waiver is?

2026-02-02 22:57 UTC, closed without merging